{
 "title": "Exim Service",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(exim_relayed_messages_total{job=\"smtprelay_eximexporter\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of mail by from host",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(exim_relayed_messages_total{instance=\"$instance\"}[$__range]))) by (from_host) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Messages Delivered",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(exim_messages_delivered{instance=\"$instance\"}[$__range]))) by (from_host) != 0"
    }
   ]
  },
  {
   "title": "Total Messages in Queue",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "exim_queue_count{instance=\"$instance\", job=\"smtprelay_eximexporter\"}"
    }
   ]
  },
  {
   "title": "Total Messages Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(exim_messages_received{instance=\"$instance\"}[$__range]))) by (from_host) != 0"
    }
   ]
  },
  {
   "title": "Total Volume Delivered (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(exim_volume_delivered_bytes{instance=\"$instance\"} [$__range]))) by (from_host)  / 1024 / 1024 != 0"
    }
   ]
  },
  {
   "title": "Total Volume Received (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(exim_volume_received_bytes{instance=\"$instance\"} [$__range]))) by (from_host)  / 1024 / 1024 != 0"
    }
   ]
  },
  {
   "title": "Total Messages Rejected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(floor(increase(exim_messages_rejected{instance=\"$instance\"}[$__range]))) by (from_host) != 0\n"
    }
   ]
  },
  {
   "title": "Exim Queue Count per server",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "(exim_queue_count{job=\"smtprelay_eximexporter\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "message reject by ip",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, sum(floor(exim_rejected_ips_message_count_total{instance=\"$instance\"})) by (ip)) != 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queue Count",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "exim_queue_email_count_total{instance=\"$instance\"} != 0",
     "legendFormat": "{{email}}"
    }
   ]
  },
  {
   "title": "host destinations messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "topk(50, exim_host_destinations_message_count_total{instance=\"$instance\"}) by (host) != 0",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Queue Time Distribution (All Messages)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "exim_queue_time_all_messages{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Queue Time Distribution (Remote Messages)",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "exim_queue_time_remote_messages{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Messages Delivered by Transport Type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "exim_transport_messages{instance=\"$instance\"}",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "Transport Volume (MB) by Type",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 24 },
   "targets": [
    {
     "expr": "exim_transport_volume_bytes{instance=\"$instance\"} / 1024 / 1024",
     "legendFormat": "{{transport}}"
    }
   ]
  },
  {
   "title": "email destinations messages",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(floor(increase(exim_relayed_messages_total{instance=\"$instance\"}[$__range]))) by (from_mail) != 0",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}